### ISSUE TITLE
Ability to make bitmaps not dependent on time

### ISSUE THREAD

**Issue by kshmir** [elcuervo/minuteman#11]
I searching for exactly what this library does, redis bitmap operations based on ruby. But it has the extra feature (which is awesome) to work with time.

Is there any way to ignore the time the bitmap is built? Or to just work with a given bitmap key?

Maybe this bitmap analysis syntax should be extracted...

It's just an idea!

**Comment by elcuervo** [comment]
Can you please check if current master suits your needs? Thanks.
