### ISSUE TITLE
suitable?

### ISSUE THREAD

**Issue by 34code** [elcuervo/minuteman#13]
Hi,

I'm playing around with minuteman and am blown away by the performance!

However, I'm wondering if minuteman would be a good solution for places where there could be a possibility of anonymous and/or duplicate events..

perhaps I could use a fixed user_id namespace for anonymous visitors?

Also, I was not able to actually inspect the data using minuteman.

I get 

```#<Minuteman::Day:0x007fe9ea324fc0 @key="minuteman_login:successful_2014-02-08">```

but cannot inspect it further.

I tried to print ```today_events``` where ```today_events = analytics.day("login:successful", Time.now.utc)```

**Comment by elcuervo** [comment]
You should check the current master to see if suits your needs
