### ISSUE TITLE
The future of Minuteman

### ISSUE THREAD

**Issue by elcuervo** [elcuervo/minuteman#14]
Well, Minuteman is now my top priority and I'm going to wrap up the work to 2.0.
I want to start a discussion on it's future features. Here is a partial list:

# Minuteman 2.0
## The core
I've been working on a lua core for minuteman that will provide several improvements, from speed to extensibility.
The basic operations in minuteman are implemented in lua so it will be trivial to re implement minuteman in other languages. After 2.0 release I plan to create a separate repo for this core.

## Anonymous users
This is by far the more requested feature. Currently the gem does some basic mapping between an event and a user id. 2.0 will rely on an internal mapping of the users, a "table" with all of them.

A user with an id will be a "normal" user but the absence of it will make it anonymous. The idea is to have a unique id (hash) of the user so who ever uses the gem can identify it.

This will allow a more understanding of your users flow in the app and a registration funnel.

## Single events
Some events can only represent quantities and not being part of a user. Adding counters you can have a simple metric of your system. Also tracking it with users can lead to a better flow in your app.

## You name it
This is your project as well, feel free to propose ideas or features.

I have faith that Minuteman 2.0 will have a ton of features and improvements :)

![Minuteman](http://i.imgur.com/S3SDTu7.gif)

Cheers!

**Comment by guyisra** [comment]
is v2 still happening?

**Comment by elcuervo** [comment]
@guyisra it will. I'm currently dealing with some family issues that do not allow me to focus on OSS as much as I'd like to. I'll do my best to make it happen soon.

**Comment by guyisra** [comment]
no rush, hope everything is ok.

**Comment by arambert** [comment]
:+1 for counters :)

**Comment by lou** [comment]
:+1:

**Comment by zywx** [comment]
:+1:

**Comment by AdrienGiboire** [comment]
:+1:

**Comment by elcuervo** [comment]
There is a [future branch](https://github.com/elcuervo/minuteman/tree/future) with all the work I've been doing. Feedback is appreciated. It's an ongoing work so please feel free to comment on it ^_^

**Comment by elcuervo** [comment]
Branch merged.
