### ISSUE TITLE
Tracking the same event for the same user

### ISSUE THREAD

**Issue by adamrubin** [elcuervo/minuteman#15]
I'm new to minuteman, and am thrashing trying to do something that should be simple. Here's my test:

```
analytics = Minuteman.new()
analytics.track("test:key", 1)
analytics.track("test:key", 1)
analytics.track("test:key", 1)
analytics.track("test:key", 2)
analytics.track("test:key", 2)
analytics.track("test:key", 2)
```
I'm tracking the same event, three times, for two users. So, now I want to get get a count of the number of times that event was tracked today, independent of the user.
```
day = analytics.day("test:key", Time.now.utc)
```
This returns a Minuteman::Day object, but when I do day.length, it returns 2 instead of what I'd expect (6). I'm assuming its returning the number of users for that key, but how do I go from that, to what I'm looking for?

**Comment by teddythetwig** [comment]
Hey guys, any update on this? Would definitely be awesome to have. @elcuervo could I pick your brain to see where you left off? Perhaps I could submit a PR.

**Comment by elcuervo** [comment]
You can now use counters: https://github.com/elcuervo/minuteman#counting
