### ISSUE TITLE
Support for Ruby 2.4

### ISSUE THREAD

**Issue by zzeligg** [elcuervo/minuteman#31]
Trying to `gem install minuteman` on Ruby 2.4. The dependency on `ohm ~>2.3.0` has itself a dependency on `msgpack ~> 0.5.12`, which does not compile because of usage of `Fixnum`. 

Both `ohm` and `msgpack` have recent versions which allows them to install for Ruby 2.4.

Could the fix simply be to update the minuteman gemspec to use a more recent version of ohm?

**Comment by elcuervo** [comment]
After way too much time this is fixed. The gem was updated.
My life took unexpected turns that drew me away from many things, including the Ruby community.
Many of my projects ended up alone, now I'm back and ready to make amends.

Thank you for the feedback.
